- name: "Backup Configurations to GIT"
  hosts: ansible
  gather_facts: False
  become: yes
  
  tasks: 
  
  - name: Init gitstore
    include_role:
      name: backup_manager
      tasks_from: includes/git_store.yml
  
  - name: Find latest backup
    find:
      paths: "/backup"
      file_type: directory
    register: found_files

  - debug: 
      var:   "{{ found_files }}"

  - name: Get latest file
    set_fact:
      latest_dir: "{{ found_files.files | sort(attribute='mtime') | last }}"

  - name: Copy files to git folder
    copy: 
      src: "{{ latest_dir.path }}"
      dest: /git_backup


