- name: "Backup Configurations to GIT"
  hosts: ansible
  gather_facts: False
  connection: local
  
  tasks: 
  
  - name: Init git_store
    include_tasks: includes/git_store.yml
  
  - name: Find latest backup dir
    find:
      paths: "/backup"
      file_type: directory
    register: found_files

  - debug: 
      var: found_files

  - name: Get latest backup dir path
    set_fact:
      latest_dir: "{{ found_files.files | sort(attribute='mtime') | last }}"

  - name: Copy files to git folder
    copy: 
      src: "{{ item }}"
      dest: "{{ git_store }}/{{ backup_manager_backup_path }}"
    with_fileglob: "{{ latest_dir.path }}/*"   
      
  - name: Sync git_store
    include_tasks: includes/git_sync.yml


