- name: "Backup Configurations to GIT"
  hosts: all
  gather_facts: False
  
  tasks: 
  
  - name: Find latest backup
    find:
      paths: "/backups"
      file_type: directory
    register: found_dirs
    delegate_to: localhost
    run_once: true

  - name: Get latest file
    set_fact:
      latest_dir: "{{ found_dirs.dirs | sort(attribute='mtime') | last }}"
    delegate_to: localhost
    run_once: true
    
  - name: Copy files to git folder
    copy: 
      src: "{{ latest_dir }}"
      dest: /git_backup
    delegate_to: localhost
    run_once: true


